spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: post-service
          uri: http://post-service:8082
          predicates:
            - Path=/posts/**
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/notifications/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      service: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
